services:
  app:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - KEY_PATH=/app/keys/
    volumes:
      - ./keys:/app/keys
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=innowise_authentification_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/setup-db-user.sh:/docker-entrypoint-initdb.d/setup-db-user.sh
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
