spring.application.name=innowise-authentification-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/innowise_authentification_service}
spring.datasource.username=${DB_USERNAME:matveyvasiluk}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=${LIQUIBASE_ENABLED:true}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

user.service.url=${USER_SERVICE_URL:http://localhost:8080}
user.service.enabled=${USER_SERVICE_ENABLED:false}
